#!/bin/sh
# Pothi installer — Linux + macOS.
#   1. drops a `pothi` script into ~/.local/bin (or ~/bin if that's older)
#   2. adds a small block to your shell rc so the script is on PATH
#   3. creates a clickable desktop launcher
#       - Linux:   ~/.local/share/applications/pothi.desktop
#       - macOS:   ~/Applications/Pothi.command (open from Launchpad / Finder)
#
# After install, run:  pothi
# That starts the local HTTP server (port 8765 by default) and opens
# Pothi in your default browser. `pothi stop` shuts the server down.
set -eu

ROOT="$(cd "$(dirname "$0")" && pwd)"
DIR="$ROOT/app"
BIN="${HOME}/.local/bin"
mkdir -p "$BIN"

# Pick the right shell rc — prefer zshrc on macOS-default zsh, else bashrc.
SHELL_RC="${HOME}/.bashrc"
if [ "${SHELL##*/}" = "zsh" ] || [ -f "${HOME}/.zshrc" ]; then
  SHELL_RC="${HOME}/.zshrc"
fi

# 1. Write the launcher script
cat > "$BIN/pothi" <<EOF
#!/bin/sh
# Auto-generated by Pothi install.sh — see $ROOT/install.sh
ROOT="$ROOT"
DIR="$DIR"
if [ -x "\$ROOT/dist/Pothi" ]; then
  exec "\$ROOT/dist/Pothi" "\$@"
fi
if [ -x "\$ROOT/dist/pothi" ]; then
  exec "\$ROOT/dist/pothi" "\$@"
fi
exec python3 "\$DIR/pothi_launcher.py" "\$@"
EOF
chmod +x "$BIN/pothi"
echo "  installed: $BIN/pothi"

# 2. Make sure ~/.local/bin is in PATH. If not, add a guarded block.
if ! echo ":$PATH:" | grep -q ":$BIN:"; then
  if ! grep -q "# >>> Pothi PATH >>>" "$SHELL_RC" 2>/dev/null; then
    cat >> "$SHELL_RC" <<EOF

# >>> Pothi PATH >>>
case ":\$PATH:" in *":$BIN:"*) ;; *) export PATH="$BIN:\$PATH" ;; esac
# <<< Pothi PATH <<<
EOF
    echo "  added: PATH update in $SHELL_RC"
  fi
fi

# 3a. Linux desktop launcher
if [ -d /usr/share/applications ] || [ "$(uname)" = "Linux" ]; then
  APPS="${HOME}/.local/share/applications"
  mkdir -p "$APPS"
  cat > "$APPS/pothi.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Pothi
GenericName=Reference Manager
Comment=Local-first reference manager
Exec=$BIN/pothi start
Terminal=false
Icon=accessories-dictionary
Categories=Office;Education;Science;
StartupNotify=true
Keywords=references;bibliography;bibtex;citations;research;
EOF
  chmod +x "$APPS/pothi.desktop" 2>/dev/null || true
  echo "  installed: $APPS/pothi.desktop"
fi

# 3b. macOS clickable .command file
if [ "$(uname)" = "Darwin" ]; then
  APPS="${HOME}/Applications"
  mkdir -p "$APPS"
  cat > "$APPS/Pothi.command" <<EOF
#!/bin/sh
"$BIN/pothi" start
echo ""
echo "Tip: Run \`pothi stop\` to shut the server down."
EOF
  chmod +x "$APPS/Pothi.command"
  echo "  installed: $APPS/Pothi.command  (open from Launchpad or Finder)"
fi

cat <<DONE

✓ Installed.

  Reload your shell:   source $SHELL_RC
  Then run:            pothi

  Or use the desktop launcher (Linux: search for "Pothi" in your menu;
  macOS: Launchpad → Pothi.command).

  Stop with:           pothi stop
DONE
